# Generated by Django 4.2.6 on 2023-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentidcard',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('prn', models.IntegerField(max_length=14)),
                ('age', models.IntegerField(max_length=3)),
                ('birth', models.DateField()),
                ('phone', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=150)),
                ('field', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('study', models.BooleanField(default=False)),
            ],
        ),
    ]
